import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import SessionProviderClientComponent from "../ui/sessionProvider"
import getServerSession from "next-auth"
import { authConfig } from "../auth.config";
import { auth } from "../auth";
const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session =  await auth()
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <StoreProvider>
          <SessionProviderClientComponent session={session} children={children}/>

        </StoreProvider>

      </body>
    </html>
  );
}
