import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "../ui/navigation";
import { fetchCategories } from "../lib/data";
import { BottomNav } from "../ui/bottom_nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await fetchCategories()
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavBar categories={categories}/>
        <div>{children}</div>
        <BottomNav/>
        </body>
    </html>
  );
}
